# Generated by Django 5.2.12 on 2026-07-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_length', models.PositiveIntegerField(default=0)),
                ('active_counters', models.PositiveIntegerField(default=0)),
                ('available_staff', models.PositiveIntegerField(default=0)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to='organizations.organization')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_snapshots', to='organizations.service')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
