# Generated by Django 5.2.12 on 2026-07-01 09:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('queue_created', 'Queue Created'), ('queue_updated', 'Queue Updated'), ('queue_deleted', 'QueueDeleted'), ('token_joined', 'Token Joined'), ('token_called', 'Token Called'), ('token_recalled', 'Token Recalled'), ('token_cancelled', 'Token Cancelled'), ('token_completed', 'Token Completed'), ('staff_login', 'Staff Login'), ('staff_logout', 'Staff Logout'), ('staff_assigned', 'Staff Assigned'), ('admin_user_created', 'Admin User Created'), ('admin_user_updated', 'Admin User Updated'), ('admin_org_updated', 'Organization Updated'), ('admin_branch_created', 'Branch Created'), ('admin_branch_updated', 'Branch Updated'), ('admin_settings_changed', 'Settings Changed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('notification_retry_attempted', 'Notification Retry Attempted'), ('notification_bulk_sent', 'Bulk Notifications Sent'), ('provider_request', 'Provider API Request'), ('provider_failure', 'Provider API Failure'), ('login_failed', 'Login Failed'), ('login_success', 'Login Successful'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('rate_limit_exceeded', 'Rate Limit Exceeded')], max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.branch')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='core_auditl_action__9597a4_idx'), models.Index(fields=['organization_id', 'created_at'], name='core_auditl_organiz_c79039_idx'), models.Index(fields=['actor_id', 'created_at'], name='core_auditl_actor_i_41600a_idx'), models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx')],
            },
        ),
    ]
