# Generated by Django 5.2.12 on 2026-07-01 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=32)),
                ('token_number', models.CharField(max_length=32)),
                ('sequence_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='waiting', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('serving_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('queue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='organizations.branch')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tokens', to='organizations.counter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_queue_tokens', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='organizations.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='organizations.service')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('branch', 'queue_date', 'sequence_number')},
            },
        ),
    ]
